# Generated by Django 5.0.7 on 2024-11-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='phone_number',
            new_name='Phone_number',
        ),
    ]
